import "./globals.css";
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import {Inter} from 'next/font/google';

const inter = Inter({ subsets : ["latin"]})

export const metadata = {
  title: "Sumbal E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Navbar/>{children}<Footer/>
        </body>
    </html>
  );
}
